package com.example.mapper;

import com.example.entity.Vcollection;
import com.example.entity.VcollectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VcollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    long countByExample(VcollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    int deleteByExample(VcollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    int insert(Vcollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    int insertSelective(Vcollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    List<Vcollection> selectByExample(VcollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Vcollection record, @Param("example") VcollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Vcollection record, @Param("example") VcollectionExample example);
}