package com.example.mapper;

import com.example.entity.Vcomment;
import com.example.entity.VcommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VcommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated
     */
    long countByExample(VcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated
     */
    int deleteByExample(VcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated
     */
    int insert(Vcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated
     */
    int insertSelective(Vcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated
     */
    List<Vcomment> selectByExample(VcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Vcomment record, @Param("example") VcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Vcomment record, @Param("example") VcommentExample example);
}