package com.example.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table action
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Action implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.type1
     *
     * @mbg.generated
     */
    private Integer type1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.type2
     *
     * @mbg.generated
     */
    private Integer type2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.type3
     *
     * @mbg.generated
     */
    private Integer type3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.type4
     *
     * @mbg.generated
     */
    private Integer type4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.type5
     *
     * @mbg.generated
     */
    private Integer type5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.type6
     *
     * @mbg.generated
     */
    private Integer type6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.type7
     *
     * @mbg.generated
     */
    private Integer type7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.id
     *
     * @return the value of action.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.id
     *
     * @param id the value for action.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.type1
     *
     * @return the value of action.type1
     *
     * @mbg.generated
     */
    public Integer getType1() {
        return type1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.type1
     *
     * @param type1 the value for action.type1
     *
     * @mbg.generated
     */
    public void setType1(Integer type1) {
        this.type1 = type1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.type2
     *
     * @return the value of action.type2
     *
     * @mbg.generated
     */
    public Integer getType2() {
        return type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.type2
     *
     * @param type2 the value for action.type2
     *
     * @mbg.generated
     */
    public void setType2(Integer type2) {
        this.type2 = type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.type3
     *
     * @return the value of action.type3
     *
     * @mbg.generated
     */
    public Integer getType3() {
        return type3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.type3
     *
     * @param type3 the value for action.type3
     *
     * @mbg.generated
     */
    public void setType3(Integer type3) {
        this.type3 = type3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.type4
     *
     * @return the value of action.type4
     *
     * @mbg.generated
     */
    public Integer getType4() {
        return type4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.type4
     *
     * @param type4 the value for action.type4
     *
     * @mbg.generated
     */
    public void setType4(Integer type4) {
        this.type4 = type4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.type5
     *
     * @return the value of action.type5
     *
     * @mbg.generated
     */
    public Integer getType5() {
        return type5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.type5
     *
     * @param type5 the value for action.type5
     *
     * @mbg.generated
     */
    public void setType5(Integer type5) {
        this.type5 = type5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.type6
     *
     * @return the value of action.type6
     *
     * @mbg.generated
     */
    public Integer getType6() {
        return type6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.type6
     *
     * @param type6 the value for action.type6
     *
     * @mbg.generated
     */
    public void setType6(Integer type6) {
        this.type6 = type6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.type7
     *
     * @return the value of action.type7
     *
     * @mbg.generated
     */
    public Integer getType7() {
        return type7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.type7
     *
     * @param type7 the value for action.type7
     *
     * @mbg.generated
     */
    public void setType7(Integer type7) {
        this.type7 = type7;
    }
}