package com.example.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dish
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Dish implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.Score
     *
     * @mbg.generated
     */
    private Float score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.CommentNumber
     *
     * @mbg.generated
     */
    private Integer commentnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.Price
     *
     * @mbg.generated
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.Favor
     *
     * @mbg.generated
     */
    private String favor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.RID
     *
     * @mbg.generated
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.Category
     *
     * @mbg.generated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dish
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.ID
     *
     * @return the value of dish.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.ID
     *
     * @param id the value for dish.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.Name
     *
     * @return the value of dish.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.Name
     *
     * @param name the value for dish.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.Score
     *
     * @return the value of dish.Score
     *
     * @mbg.generated
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.Score
     *
     * @param score the value for dish.Score
     *
     * @mbg.generated
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.CommentNumber
     *
     * @return the value of dish.CommentNumber
     *
     * @mbg.generated
     */
    public Integer getCommentnumber() {
        return commentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.CommentNumber
     *
     * @param commentnumber the value for dish.CommentNumber
     *
     * @mbg.generated
     */
    public void setCommentnumber(Integer commentnumber) {
        this.commentnumber = commentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.Price
     *
     * @return the value of dish.Price
     *
     * @mbg.generated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.Price
     *
     * @param price the value for dish.Price
     *
     * @mbg.generated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.Favor
     *
     * @return the value of dish.Favor
     *
     * @mbg.generated
     */
    public String getFavor() {
        return favor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.Favor
     *
     * @param favor the value for dish.Favor
     *
     * @mbg.generated
     */
    public void setFavor(String favor) {
        this.favor = favor == null ? null : favor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.RID
     *
     * @return the value of dish.RID
     *
     * @mbg.generated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.RID
     *
     * @param rid the value for dish.RID
     *
     * @mbg.generated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.Category
     *
     * @return the value of dish.Category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.Category
     *
     * @param category the value for dish.Category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }
}