package com.example.entity;

import java.util.ArrayList;
import java.util.List;

public class DishExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dish
     *
     * @mbg.generated
     */
    protected int startRow;

    protected int pageSize;


    public int getStartRow() {
        return startRow;
    }

    public void setStartRow(int startRow) {
        this.startRow = startRow;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dish
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dish
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    public DishExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dish
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("Name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("Name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("Name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("Name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("Name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("Name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("Name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("Name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("Name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("Name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("Name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("Name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("Name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("Name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("Score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("Score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Float value) {
            addCriterion("Score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Float value) {
            addCriterion("Score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Float value) {
            addCriterion("Score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Float value) {
            addCriterion("Score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Float value) {
            addCriterion("Score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Float value) {
            addCriterion("Score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Float> values) {
            addCriterion("Score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Float> values) {
            addCriterion("Score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Float value1, Float value2) {
            addCriterion("Score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Float value1, Float value2) {
            addCriterion("Score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andCommentnumberIsNull() {
            addCriterion("CommentNumber is null");
            return (Criteria) this;
        }

        public Criteria andCommentnumberIsNotNull() {
            addCriterion("CommentNumber is not null");
            return (Criteria) this;
        }

        public Criteria andCommentnumberEqualTo(Integer value) {
            addCriterion("CommentNumber =", value, "commentnumber");
            return (Criteria) this;
        }

        public Criteria andCommentnumberNotEqualTo(Integer value) {
            addCriterion("CommentNumber <>", value, "commentnumber");
            return (Criteria) this;
        }

        public Criteria andCommentnumberGreaterThan(Integer value) {
            addCriterion("CommentNumber >", value, "commentnumber");
            return (Criteria) this;
        }

        public Criteria andCommentnumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("CommentNumber >=", value, "commentnumber");
            return (Criteria) this;
        }

        public Criteria andCommentnumberLessThan(Integer value) {
            addCriterion("CommentNumber <", value, "commentnumber");
            return (Criteria) this;
        }

        public Criteria andCommentnumberLessThanOrEqualTo(Integer value) {
            addCriterion("CommentNumber <=", value, "commentnumber");
            return (Criteria) this;
        }

        public Criteria andCommentnumberIn(List<Integer> values) {
            addCriterion("CommentNumber in", values, "commentnumber");
            return (Criteria) this;
        }

        public Criteria andCommentnumberNotIn(List<Integer> values) {
            addCriterion("CommentNumber not in", values, "commentnumber");
            return (Criteria) this;
        }

        public Criteria andCommentnumberBetween(Integer value1, Integer value2) {
            addCriterion("CommentNumber between", value1, value2, "commentnumber");
            return (Criteria) this;
        }

        public Criteria andCommentnumberNotBetween(Integer value1, Integer value2) {
            addCriterion("CommentNumber not between", value1, value2, "commentnumber");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("Price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("Price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Float value) {
            addCriterion("Price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Float value) {
            addCriterion("Price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Float value) {
            addCriterion("Price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("Price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Float value) {
            addCriterion("Price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Float value) {
            addCriterion("Price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Float> values) {
            addCriterion("Price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Float> values) {
            addCriterion("Price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Float value1, Float value2) {
            addCriterion("Price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Float value1, Float value2) {
            addCriterion("Price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andFavorIsNull() {
            addCriterion("Favor is null");
            return (Criteria) this;
        }

        public Criteria andFavorIsNotNull() {
            addCriterion("Favor is not null");
            return (Criteria) this;
        }

        public Criteria andFavorEqualTo(String value) {
            addCriterion("Favor =", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorNotEqualTo(String value) {
            addCriterion("Favor <>", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorGreaterThan(String value) {
            addCriterion("Favor >", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorGreaterThanOrEqualTo(String value) {
            addCriterion("Favor >=", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorLessThan(String value) {
            addCriterion("Favor <", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorLessThanOrEqualTo(String value) {
            addCriterion("Favor <=", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorLike(String value) {
            addCriterion("Favor like", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorNotLike(String value) {
            addCriterion("Favor not like", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorIn(List<String> values) {
            addCriterion("Favor in", values, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorNotIn(List<String> values) {
            addCriterion("Favor not in", values, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorBetween(String value1, String value2) {
            addCriterion("Favor between", value1, value2, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorNotBetween(String value1, String value2) {
            addCriterion("Favor not between", value1, value2, "favor");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("Category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("Category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("Category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("Category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("Category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("Category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("Category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("Category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("Category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("Category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("Category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("Category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("Category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("Category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameIsNull() {
            addCriterion("restaurantname is null");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameIsNotNull() {
            addCriterion("restaurantname is not null");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameEqualTo(String value) {
            addCriterion("restaurantname =", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameNotEqualTo(String value) {
            addCriterion("restaurantname <>", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameGreaterThan(String value) {
            addCriterion("restaurantname >", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameGreaterThanOrEqualTo(String value) {
            addCriterion("restaurantname >=", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameLessThan(String value) {
            addCriterion("restaurantname <", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameLessThanOrEqualTo(String value) {
            addCriterion("restaurantname <=", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameLike(String value) {
            addCriterion("restaurantname like", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameNotLike(String value) {
            addCriterion("restaurantname not like", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameIn(List<String> values) {
            addCriterion("restaurantname in", values, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameNotIn(List<String> values) {
            addCriterion("restaurantname not in", values, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameBetween(String value1, String value2) {
            addCriterion("restaurantname between", value1, value2, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameNotBetween(String value1, String value2) {
            addCriterion("restaurantname not between", value1, value2, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationIsNull() {
            addCriterion("restaurantlocation is null");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationIsNotNull() {
            addCriterion("restaurantlocation is not null");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationEqualTo(String value) {
            addCriterion("restaurantlocation =", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationNotEqualTo(String value) {
            addCriterion("restaurantlocation <>", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationGreaterThan(String value) {
            addCriterion("restaurantlocation >", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationGreaterThanOrEqualTo(String value) {
            addCriterion("restaurantlocation >=", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationLessThan(String value) {
            addCriterion("restaurantlocation <", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationLessThanOrEqualTo(String value) {
            addCriterion("restaurantlocation <=", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationLike(String value) {
            addCriterion("restaurantlocation like", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationNotLike(String value) {
            addCriterion("restaurantlocation not like", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationIn(List<String> values) {
            addCriterion("restaurantlocation in", values, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationNotIn(List<String> values) {
            addCriterion("restaurantlocation not in", values, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationBetween(String value1, String value2) {
            addCriterion("restaurantlocation between", value1, value2, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationNotBetween(String value1, String value2) {
            addCriterion("restaurantlocation not between", value1, value2, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andPicurlIsNull() {
            addCriterion("picurl is null");
            return (Criteria) this;
        }

        public Criteria andPicurlIsNotNull() {
            addCriterion("picurl is not null");
            return (Criteria) this;
        }

        public Criteria andPicurlEqualTo(String value) {
            addCriterion("picurl =", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotEqualTo(String value) {
            addCriterion("picurl <>", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlGreaterThan(String value) {
            addCriterion("picurl >", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlGreaterThanOrEqualTo(String value) {
            addCriterion("picurl >=", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLessThan(String value) {
            addCriterion("picurl <", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLessThanOrEqualTo(String value) {
            addCriterion("picurl <=", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLike(String value) {
            addCriterion("picurl like", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotLike(String value) {
            addCriterion("picurl not like", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlIn(List<String> values) {
            addCriterion("picurl in", values, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotIn(List<String> values) {
            addCriterion("picurl not in", values, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlBetween(String value1, String value2) {
            addCriterion("picurl between", value1, value2, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotBetween(String value1, String value2) {
            addCriterion("picurl not between", value1, value2, "picurl");
            return (Criteria) this;
        }

        public Criteria andSmallpicIsNull() {
            addCriterion("smallpic is null");
            return (Criteria) this;
        }

        public Criteria andSmallpicIsNotNull() {
            addCriterion("smallpic is not null");
            return (Criteria) this;
        }

        public Criteria andSmallpicEqualTo(String value) {
            addCriterion("smallpic =", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicNotEqualTo(String value) {
            addCriterion("smallpic <>", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicGreaterThan(String value) {
            addCriterion("smallpic >", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicGreaterThanOrEqualTo(String value) {
            addCriterion("smallpic >=", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicLessThan(String value) {
            addCriterion("smallpic <", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicLessThanOrEqualTo(String value) {
            addCriterion("smallpic <=", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicLike(String value) {
            addCriterion("smallpic like", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicNotLike(String value) {
            addCriterion("smallpic not like", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicIn(List<String> values) {
            addCriterion("smallpic in", values, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicNotIn(List<String> values) {
            addCriterion("smallpic not in", values, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicBetween(String value1, String value2) {
            addCriterion("smallpic between", value1, value2, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicNotBetween(String value1, String value2) {
            addCriterion("smallpic not between", value1, value2, "smallpic");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dish
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dish
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}