package com.example.entity;

import java.util.ArrayList;
import java.util.List;

public class VcollectionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    public VcollectionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDishidIsNull() {
            addCriterion("dishid is null");
            return (Criteria) this;
        }

        public Criteria andDishidIsNotNull() {
            addCriterion("dishid is not null");
            return (Criteria) this;
        }

        public Criteria andDishidEqualTo(Integer value) {
            addCriterion("dishid =", value, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidNotEqualTo(Integer value) {
            addCriterion("dishid <>", value, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidGreaterThan(Integer value) {
            addCriterion("dishid >", value, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidGreaterThanOrEqualTo(Integer value) {
            addCriterion("dishid >=", value, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidLessThan(Integer value) {
            addCriterion("dishid <", value, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidLessThanOrEqualTo(Integer value) {
            addCriterion("dishid <=", value, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidIn(List<Integer> values) {
            addCriterion("dishid in", values, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidNotIn(List<Integer> values) {
            addCriterion("dishid not in", values, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidBetween(Integer value1, Integer value2) {
            addCriterion("dishid between", value1, value2, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidNotBetween(Integer value1, Integer value2) {
            addCriterion("dishid not between", value1, value2, "dishid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("userid like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("userid not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andDishnameIsNull() {
            addCriterion("dishname is null");
            return (Criteria) this;
        }

        public Criteria andDishnameIsNotNull() {
            addCriterion("dishname is not null");
            return (Criteria) this;
        }

        public Criteria andDishnameEqualTo(String value) {
            addCriterion("dishname =", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameNotEqualTo(String value) {
            addCriterion("dishname <>", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameGreaterThan(String value) {
            addCriterion("dishname >", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameGreaterThanOrEqualTo(String value) {
            addCriterion("dishname >=", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameLessThan(String value) {
            addCriterion("dishname <", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameLessThanOrEqualTo(String value) {
            addCriterion("dishname <=", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameLike(String value) {
            addCriterion("dishname like", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameNotLike(String value) {
            addCriterion("dishname not like", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameIn(List<String> values) {
            addCriterion("dishname in", values, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameNotIn(List<String> values) {
            addCriterion("dishname not in", values, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameBetween(String value1, String value2) {
            addCriterion("dishname between", value1, value2, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameNotBetween(String value1, String value2) {
            addCriterion("dishname not between", value1, value2, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishscoreIsNull() {
            addCriterion("dishscore is null");
            return (Criteria) this;
        }

        public Criteria andDishscoreIsNotNull() {
            addCriterion("dishscore is not null");
            return (Criteria) this;
        }

        public Criteria andDishscoreEqualTo(Float value) {
            addCriterion("dishscore =", value, "dishscore");
            return (Criteria) this;
        }

        public Criteria andDishscoreNotEqualTo(Float value) {
            addCriterion("dishscore <>", value, "dishscore");
            return (Criteria) this;
        }

        public Criteria andDishscoreGreaterThan(Float value) {
            addCriterion("dishscore >", value, "dishscore");
            return (Criteria) this;
        }

        public Criteria andDishscoreGreaterThanOrEqualTo(Float value) {
            addCriterion("dishscore >=", value, "dishscore");
            return (Criteria) this;
        }

        public Criteria andDishscoreLessThan(Float value) {
            addCriterion("dishscore <", value, "dishscore");
            return (Criteria) this;
        }

        public Criteria andDishscoreLessThanOrEqualTo(Float value) {
            addCriterion("dishscore <=", value, "dishscore");
            return (Criteria) this;
        }

        public Criteria andDishscoreIn(List<Float> values) {
            addCriterion("dishscore in", values, "dishscore");
            return (Criteria) this;
        }

        public Criteria andDishscoreNotIn(List<Float> values) {
            addCriterion("dishscore not in", values, "dishscore");
            return (Criteria) this;
        }

        public Criteria andDishscoreBetween(Float value1, Float value2) {
            addCriterion("dishscore between", value1, value2, "dishscore");
            return (Criteria) this;
        }

        public Criteria andDishscoreNotBetween(Float value1, Float value2) {
            addCriterion("dishscore not between", value1, value2, "dishscore");
            return (Criteria) this;
        }

        public Criteria andDishcommentnumberIsNull() {
            addCriterion("dishcommentnumber is null");
            return (Criteria) this;
        }

        public Criteria andDishcommentnumberIsNotNull() {
            addCriterion("dishcommentnumber is not null");
            return (Criteria) this;
        }

        public Criteria andDishcommentnumberEqualTo(Integer value) {
            addCriterion("dishcommentnumber =", value, "dishcommentnumber");
            return (Criteria) this;
        }

        public Criteria andDishcommentnumberNotEqualTo(Integer value) {
            addCriterion("dishcommentnumber <>", value, "dishcommentnumber");
            return (Criteria) this;
        }

        public Criteria andDishcommentnumberGreaterThan(Integer value) {
            addCriterion("dishcommentnumber >", value, "dishcommentnumber");
            return (Criteria) this;
        }

        public Criteria andDishcommentnumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("dishcommentnumber >=", value, "dishcommentnumber");
            return (Criteria) this;
        }

        public Criteria andDishcommentnumberLessThan(Integer value) {
            addCriterion("dishcommentnumber <", value, "dishcommentnumber");
            return (Criteria) this;
        }

        public Criteria andDishcommentnumberLessThanOrEqualTo(Integer value) {
            addCriterion("dishcommentnumber <=", value, "dishcommentnumber");
            return (Criteria) this;
        }

        public Criteria andDishcommentnumberIn(List<Integer> values) {
            addCriterion("dishcommentnumber in", values, "dishcommentnumber");
            return (Criteria) this;
        }

        public Criteria andDishcommentnumberNotIn(List<Integer> values) {
            addCriterion("dishcommentnumber not in", values, "dishcommentnumber");
            return (Criteria) this;
        }

        public Criteria andDishcommentnumberBetween(Integer value1, Integer value2) {
            addCriterion("dishcommentnumber between", value1, value2, "dishcommentnumber");
            return (Criteria) this;
        }

        public Criteria andDishcommentnumberNotBetween(Integer value1, Integer value2) {
            addCriterion("dishcommentnumber not between", value1, value2, "dishcommentnumber");
            return (Criteria) this;
        }

        public Criteria andDishpriceIsNull() {
            addCriterion("dishprice is null");
            return (Criteria) this;
        }

        public Criteria andDishpriceIsNotNull() {
            addCriterion("dishprice is not null");
            return (Criteria) this;
        }

        public Criteria andDishpriceEqualTo(Float value) {
            addCriterion("dishprice =", value, "dishprice");
            return (Criteria) this;
        }

        public Criteria andDishpriceNotEqualTo(Float value) {
            addCriterion("dishprice <>", value, "dishprice");
            return (Criteria) this;
        }

        public Criteria andDishpriceGreaterThan(Float value) {
            addCriterion("dishprice >", value, "dishprice");
            return (Criteria) this;
        }

        public Criteria andDishpriceGreaterThanOrEqualTo(Float value) {
            addCriterion("dishprice >=", value, "dishprice");
            return (Criteria) this;
        }

        public Criteria andDishpriceLessThan(Float value) {
            addCriterion("dishprice <", value, "dishprice");
            return (Criteria) this;
        }

        public Criteria andDishpriceLessThanOrEqualTo(Float value) {
            addCriterion("dishprice <=", value, "dishprice");
            return (Criteria) this;
        }

        public Criteria andDishpriceIn(List<Float> values) {
            addCriterion("dishprice in", values, "dishprice");
            return (Criteria) this;
        }

        public Criteria andDishpriceNotIn(List<Float> values) {
            addCriterion("dishprice not in", values, "dishprice");
            return (Criteria) this;
        }

        public Criteria andDishpriceBetween(Float value1, Float value2) {
            addCriterion("dishprice between", value1, value2, "dishprice");
            return (Criteria) this;
        }

        public Criteria andDishpriceNotBetween(Float value1, Float value2) {
            addCriterion("dishprice not between", value1, value2, "dishprice");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameIsNull() {
            addCriterion("restaurantname is null");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameIsNotNull() {
            addCriterion("restaurantname is not null");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameEqualTo(String value) {
            addCriterion("restaurantname =", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameNotEqualTo(String value) {
            addCriterion("restaurantname <>", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameGreaterThan(String value) {
            addCriterion("restaurantname >", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameGreaterThanOrEqualTo(String value) {
            addCriterion("restaurantname >=", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameLessThan(String value) {
            addCriterion("restaurantname <", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameLessThanOrEqualTo(String value) {
            addCriterion("restaurantname <=", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameLike(String value) {
            addCriterion("restaurantname like", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameNotLike(String value) {
            addCriterion("restaurantname not like", value, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameIn(List<String> values) {
            addCriterion("restaurantname in", values, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameNotIn(List<String> values) {
            addCriterion("restaurantname not in", values, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameBetween(String value1, String value2) {
            addCriterion("restaurantname between", value1, value2, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantnameNotBetween(String value1, String value2) {
            addCriterion("restaurantname not between", value1, value2, "restaurantname");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationIsNull() {
            addCriterion("restaurantlocation is null");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationIsNotNull() {
            addCriterion("restaurantlocation is not null");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationEqualTo(String value) {
            addCriterion("restaurantlocation =", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationNotEqualTo(String value) {
            addCriterion("restaurantlocation <>", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationGreaterThan(String value) {
            addCriterion("restaurantlocation >", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationGreaterThanOrEqualTo(String value) {
            addCriterion("restaurantlocation >=", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationLessThan(String value) {
            addCriterion("restaurantlocation <", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationLessThanOrEqualTo(String value) {
            addCriterion("restaurantlocation <=", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationLike(String value) {
            addCriterion("restaurantlocation like", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationNotLike(String value) {
            addCriterion("restaurantlocation not like", value, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationIn(List<String> values) {
            addCriterion("restaurantlocation in", values, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationNotIn(List<String> values) {
            addCriterion("restaurantlocation not in", values, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationBetween(String value1, String value2) {
            addCriterion("restaurantlocation between", value1, value2, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andRestaurantlocationNotBetween(String value1, String value2) {
            addCriterion("restaurantlocation not between", value1, value2, "restaurantlocation");
            return (Criteria) this;
        }

        public Criteria andFavorIsNull() {
            addCriterion("favor is null");
            return (Criteria) this;
        }

        public Criteria andFavorIsNotNull() {
            addCriterion("favor is not null");
            return (Criteria) this;
        }

        public Criteria andFavorEqualTo(String value) {
            addCriterion("favor =", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorNotEqualTo(String value) {
            addCriterion("favor <>", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorGreaterThan(String value) {
            addCriterion("favor >", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorGreaterThanOrEqualTo(String value) {
            addCriterion("favor >=", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorLessThan(String value) {
            addCriterion("favor <", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorLessThanOrEqualTo(String value) {
            addCriterion("favor <=", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorLike(String value) {
            addCriterion("favor like", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorNotLike(String value) {
            addCriterion("favor not like", value, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorIn(List<String> values) {
            addCriterion("favor in", values, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorNotIn(List<String> values) {
            addCriterion("favor not in", values, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorBetween(String value1, String value2) {
            addCriterion("favor between", value1, value2, "favor");
            return (Criteria) this;
        }

        public Criteria andFavorNotBetween(String value1, String value2) {
            addCriterion("favor not between", value1, value2, "favor");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andPicurlIsNull() {
            addCriterion("picurl is null");
            return (Criteria) this;
        }

        public Criteria andPicurlIsNotNull() {
            addCriterion("picurl is not null");
            return (Criteria) this;
        }

        public Criteria andPicurlEqualTo(String value) {
            addCriterion("picurl =", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotEqualTo(String value) {
            addCriterion("picurl <>", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlGreaterThan(String value) {
            addCriterion("picurl >", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlGreaterThanOrEqualTo(String value) {
            addCriterion("picurl >=", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLessThan(String value) {
            addCriterion("picurl <", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLessThanOrEqualTo(String value) {
            addCriterion("picurl <=", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLike(String value) {
            addCriterion("picurl like", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotLike(String value) {
            addCriterion("picurl not like", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlIn(List<String> values) {
            addCriterion("picurl in", values, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotIn(List<String> values) {
            addCriterion("picurl not in", values, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlBetween(String value1, String value2) {
            addCriterion("picurl between", value1, value2, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotBetween(String value1, String value2) {
            addCriterion("picurl not between", value1, value2, "picurl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vcollection
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vcollection
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}