package com.example.entity;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table vzan
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Vzan implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vzan.zid
     *
     * @mbg.generated
     */
    private Integer zid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vzan.did
     *
     * @mbg.generated
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vzan.dname
     *
     * @mbg.generated
     */
    private String dname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vzan.score
     *
     * @mbg.generated
     */
    private Float score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vzan.CommentNumber
     *
     * @mbg.generated
     */
    private Integer commentnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vzan.Price
     *
     * @mbg.generated
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vzan.Favor
     *
     * @mbg.generated
     */
    private String favor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vzan.Category
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vzan.restaurantname
     *
     * @mbg.generated
     */
    private String restaurantname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vzan.restaurantlocation
     *
     * @mbg.generated
     */
    private String restaurantlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vzan.picurl
     *
     * @mbg.generated
     */
    private String picurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vzan.smallpic
     *
     * @mbg.generated
     */
    private String smallpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vzan.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vzan
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vzan.zid
     *
     * @return the value of vzan.zid
     *
     * @mbg.generated
     */
    public Integer getZid() {
        return zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vzan.zid
     *
     * @param zid the value for vzan.zid
     *
     * @mbg.generated
     */
    public void setZid(Integer zid) {
        this.zid = zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vzan.did
     *
     * @return the value of vzan.did
     *
     * @mbg.generated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vzan.did
     *
     * @param did the value for vzan.did
     *
     * @mbg.generated
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vzan.dname
     *
     * @return the value of vzan.dname
     *
     * @mbg.generated
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vzan.dname
     *
     * @param dname the value for vzan.dname
     *
     * @mbg.generated
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vzan.score
     *
     * @return the value of vzan.score
     *
     * @mbg.generated
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vzan.score
     *
     * @param score the value for vzan.score
     *
     * @mbg.generated
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vzan.CommentNumber
     *
     * @return the value of vzan.CommentNumber
     *
     * @mbg.generated
     */
    public Integer getCommentnumber() {
        return commentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vzan.CommentNumber
     *
     * @param commentnumber the value for vzan.CommentNumber
     *
     * @mbg.generated
     */
    public void setCommentnumber(Integer commentnumber) {
        this.commentnumber = commentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vzan.Price
     *
     * @return the value of vzan.Price
     *
     * @mbg.generated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vzan.Price
     *
     * @param price the value for vzan.Price
     *
     * @mbg.generated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vzan.Favor
     *
     * @return the value of vzan.Favor
     *
     * @mbg.generated
     */
    public String getFavor() {
        return favor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vzan.Favor
     *
     * @param favor the value for vzan.Favor
     *
     * @mbg.generated
     */
    public void setFavor(String favor) {
        this.favor = favor == null ? null : favor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vzan.Category
     *
     * @return the value of vzan.Category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vzan.Category
     *
     * @param category the value for vzan.Category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vzan.restaurantname
     *
     * @return the value of vzan.restaurantname
     *
     * @mbg.generated
     */
    public String getRestaurantname() {
        return restaurantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vzan.restaurantname
     *
     * @param restaurantname the value for vzan.restaurantname
     *
     * @mbg.generated
     */
    public void setRestaurantname(String restaurantname) {
        this.restaurantname = restaurantname == null ? null : restaurantname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vzan.restaurantlocation
     *
     * @return the value of vzan.restaurantlocation
     *
     * @mbg.generated
     */
    public String getRestaurantlocation() {
        return restaurantlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vzan.restaurantlocation
     *
     * @param restaurantlocation the value for vzan.restaurantlocation
     *
     * @mbg.generated
     */
    public void setRestaurantlocation(String restaurantlocation) {
        this.restaurantlocation = restaurantlocation == null ? null : restaurantlocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vzan.picurl
     *
     * @return the value of vzan.picurl
     *
     * @mbg.generated
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vzan.picurl
     *
     * @param picurl the value for vzan.picurl
     *
     * @mbg.generated
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vzan.smallpic
     *
     * @return the value of vzan.smallpic
     *
     * @mbg.generated
     */
    public String getSmallpic() {
        return smallpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vzan.smallpic
     *
     * @param smallpic the value for vzan.smallpic
     *
     * @mbg.generated
     */
    public void setSmallpic(String smallpic) {
        this.smallpic = smallpic == null ? null : smallpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vzan.uid
     *
     * @return the value of vzan.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vzan.uid
     *
     * @param uid the value for vzan.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }
}